### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100, "tom"],
  "methodSign": "findById@2_int_java.lang.String"
}

### 多参数传入
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100, "张飞"]
}
