### 获取 8088 用户信息
GET http://localhost:8088/?id=34

### 通过调用 8088 调用超时接口
GET http://localhost:8088/find?timeout=1000

### 通过调用 8081 设置超时接口
GET http://localhost:8082/timeoutPorts?timeoutPorts=8082,8084

### 获取用户信息
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100],
  "methodSign": "findById@1_int"
}

### 多参数传入
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.lokn.knrpc.demo.api.UserService",
  "method": "findById",
  "args": [100, "张飞"]
}
