server:
  port: 8088

knrpc:
  zk:
    providers: http://localhost:8081/,http://localhost:8082/,http://localhost:8083/
    zkService: localhost:2181
    zkRoot: knrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    reties: 2
    timeout: 1000
    grayRatio: 10 # 0-100
    faultLimit: 100
    halfOpenInitialDelay: 10_000
    halfOpenDelay: 60_000

knregistry:
  servers: http://localhost:8484

logging:
  level:
    root: error
    cn.lokn.knrpc: debug
    com.ctrip: debug

# apollo 配置中心
app:
  id: lokn
apollo:
  cache-dir: /opt/data/
  cluster: default
  meta: http://kimmking.cn:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: lokn
    egerLoadCache:
      enabled: false
