server:
  port: 8081

knrpc:
  zk:
    zkRoot: knrpc
    zkService: localhost:2181
  app:
    env: dev
    id: app1
    namespace: public
  provider:
    metas:
      dc: bj
      gray: false
      tc: 20
      unit: B001

knregistry:
  services: http://localhost:8484

logging:
  level:
    root: error
    cn.lokn.knrpc: debug
    com.ctrip: info

# apollo 配置中心
app:
  id: lokn
apollo:
  cache-dir: /opt/data/
  cluster: default
  meta: http://kimmking.cn:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: lokn
    eagerLoadCache:
      enabled: false

