server:
  port: 8081

knrpc:
  zkService: localhost:2181
  zkRoot: knrpc

app:
  id: app1
  namespace: public
  env: dev
  metas: "{'gray': false, 'dc': 'bj', 'unit': 'B001', 'tc':''}"
#    gray: false
#    dc: bj      # 机房
#    unit: B001  # 单元

logging:
  level:
    root: error
    cn.lokn.knrpc: debug