server:
  port: 8081

knrpc:
  zk:
    zkService: localhost:2181
    zkRoot: knrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      gray: false # 是否进行灰度发布。true-是；false-否
      dc: bj      # 机房
      unit: B001  # 单元
      tc: 20        # 流量控制。默认 30秒内20次，传入0或-1 表示不进行流量控制

logging:
  level:
    root: error
    cn.lokn.knrpc: info